### ISSUE TITLE
pydantic error for invalid identifier

### ISSUE THREAD

**Issue by dreamerlzl** [eyurtsev/kor#189]
Problem: it seems that the identifier used in `kor` doesn't comply to the convention in pydantic and that cause the following issue:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../.cache/pypoetry/virtualenvs/job-aggregator-u73mtD9n-py3.11/lib/python3.11/site-packages/kor/adapters.py:151: in from_pydantic
    schema = _translate_pydantic_to_kor(
../../../.cache/pypoetry/virtualenvs/job-aggregator-u73mtD9n-py3.11/lib/python3.11/site-packages/kor/adapters.py:109: in _translate_pydantic_to_kor
    options=[Option(id=choice.value) for choice in enum_choices],
../../../.cache/pypoetry/virtualenvs/job-aggregator-u73mtD9n-py3.11/lib/python3.11/site-packages/kor/adapters.py:109: in <listcomp>
    options=[Option(id=choice.value) for choice in enum_choices],
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for Option
E   id
E     `<built-in function id>` is not a valid identifier. Please only use lower cased a-z, _ or the digits 0-9 (type=value_error)

pydantic/main.py:341: ValidationError
```

My pyproject.toml:

```toml
[tool.poetry]
name = "job-aggregator"
version = "0.1.0"
description = ""
authors = ["dreamerlzl <875350879@qq.com>"]
readme = "README.md"
packages = [{include = "job_aggregator"}]

[tool.poetry.dependencies]
python = "^3.8.1"
beautifulsoup4 = "^4.11.2"
html5lib = "^1.1"
requests = "^2.28.2"
sqlitedict = "^2.1.0"
python-telegram-bot = "^20.1"
redis = "^4.5.5"
kor = "^0.12.0"
pydantic = "1.10.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

How to reproduce: 
```python
import enum
from pydantic import BaseModel
from kor import from_pydantic

class Bar(enum.Enum):
    A = "1 2 3"


class Foo(BaseModel):
    bar: Bar


from_pydantic(Foo)
```
